import { StyleSheet } from 'react-native';
import { Color } from '../../components/Colors';

const styles = StyleSheet.create({
    container_center: {
        flex: 1,
        padding: 30,
        justifyContent: 'center',
        backgroundColor: '#f4fff7',
        width: '100%',
        height: '100%',
        position: 'relative',
    },
    container_top: {
        flex: 1,
        padding: 30,
        backgroundColor: '#fcfffc',
        width: '100%',
        height: '100%',
        paddingTop: 80,
        paddingBottom: 120,
        justifyContent: 'flex-start',
    },
    text_head1: {
        fontSize: 26,
        color: Color.text1,
        fontFamily: 'Kanit_600SemiBold',
    },
    text_head2: {
        fontSize: 24,
        color: Color.text1,
        fontFamily: 'Kanit_400Regular',
    },
    text_head3: {
        fontSize: 18,
        color: Color.text3,
        margin: 0,
        padding: 0,
        fontFamily: 'Kanit_400Regular',
    },
    text_head3_white: {
        color: '#fff',
        fontSize: 16,
        fontFamily: 'Kanit_400Regular',
    },
    text_head4: {
        fontSize: 16,
        color: Color.text3,
        marginVertical: 2,
        fontFamily: 'Kanit_400Regular',
    },
    text_head4_gray: {
        fontSize: 18,
        marginVertical: 6,
        color: Color.text4,
        fontFamily: 'Kanit_400Regular',
    },
    text_head5_red: {
        color: '#c44',
        fontSize: 16,
        fontFamily: 'Kanit_400Regular',
    },
    input: {
        borderWidth: 1,
        borderColor: '#e6e6e6',
        borderRadius: 6,
        padding: 12,
        marginBottom: 4,
        fontSize: 16,
        backgroundColor: '#fff',
        elevation: 1,
        fontFamily: 'Kanit_400Regular',
        borderBottomColor: '#2e6b50',
        borderBottomWidth: 3,
    },
    button_green: {
        backgroundColor: '#2e6b50',
        paddingVertical: 14,
        borderRadius: 4,
        alignItems: 'center',
        marginBottom: 15,
    },
    button_green_text: {
        color: '#fff',
        fontSize: 16,
        fontFamily: 'Kanit_400Regular',
    },
    button_white: {
        backgroundColor: '#fff',
        borderRadius: 4,
        borderColor: '#ddd',
        borderWidth: 1,
        paddingVertical: 12,
        alignItems: 'center',
        marginBottom: 20,
    },
    button_gray: {
        backgroundColor: '#eaeaea',
        paddingVertical: 14,
        borderRadius: 4,
        alignItems: 'center',
    },
    button_gray_text: {
        color: '#888',
        fontSize: 16,
        fontFamily: 'Kanit_400Regular',
    },
    nextIcon: {
        position: 'absolute',
        bottom: 25,
        right: 25,
        display: 'flex',
        alignItems: 'center',
        flexDirection: 'row',
    },
    nextIcon_Text: {
        fontSize: 24,
        color: '#000',
        fontFamily: 'Kanit_400Regular',
        marginRight: 10,
    },
})

const setting_styles = StyleSheet.create({
    container: styles.container_top,
    header: {
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 10,
        // backgroundColor: Color.main,
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        paddingTop: 60,
        paddingHorizontal: 30,
        borderBottomRightRadius: 20,
        borderBottomLeftRadius: 20,
    },

    headerImage: {
        width: '20%',
        height: '70%',
        resizeMode: 'contain',
        alignSelf: 'flex-end',
        position: 'absolute',
        bottom: 20,
        right: 0,
        marginHorizontal: 30,
    },
    text_head1: styles.text_head1,
    text_head3: styles.text_head3,
    text_head4: styles.text_head4,
    text_head4_gray: styles.text_head4_gray,
    calendar: {
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'stretch',
        marginBottom: 10,
        elevation: 3,
        borderRadius: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        backgroundColor: '#fff',
        paddingHorizontal: 10,
    },
    calendar_head: {
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 5,
    },
    listItem: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: 10,
    },
    listItemText: styles.text_head2,
    listIconDone: {
        color: 'green',
        fontSize: 25,
    },
    listIconNot: {
        color: 'red',
        fontSize: 25,
    },
    listIconNow: {
        color: '#999',
        fontSize: 20,
        paddingBottom: 2,
    },
    plusIcon: {
        position: 'absolute',
        bottom: 110,
        right: 20,
        padding: 10,
        borderRadius: 50,
        backgroundColor: '#2e6b50'
    },
    modal: {
        justifyContent: 'flex-end',
        margin: 0,
    },
    title: {
        fontSize: 20,
        fontWeight: 'bold',
        fontFamily: 'Kanit',
        marginBottom: 16,
    },
    label: {
        fontSize: 16,
        fontFamily: 'Kanit',
        marginTop: 12,
    },
    buttonRow: {
        flexDirection: 'row',
        gap: 8,
        marginVertical: 8,
    },
    activeButton: {
        backgroundColor: '#1c4c3f',
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 6,
    },
    inactiveButton: {
        backgroundColor: '#eee',
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 6,
    },
    buttonText: {
        color: 'white',
        fontFamily: 'Kanit',
    },
    input: {
        borderWidth: 1,
        borderColor: '#ccc',
        borderRadius: 6,
        padding: 8,
        marginVertical: 8,
        fontFamily: 'Kanit',
        fontSize: 18,
        width: '100%',
    },
    picker: {
        borderWidth: 1,
        borderColor: '#ccc',
        borderRadius: 6,
        padding: 8,
        marginVertical: 8,
        fontFamily: 'Kanit',
        fontSize: 18,
        width: '100%',
    },
    confirmButton: {
        backgroundColor: '#1c4c3f',
        borderRadius: 8,
        padding: 12,
        alignItems: 'center',
        marginTop: 24,
    },
    confirmText: {
        color: 'white',
        fontSize: 16,
        fontFamily: 'Kanit',
    },
});

export default { setting_styles };